apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: nginx-custom
          image: 127041487502.dkr.ecr.us-east-1.amazonaws.com/econstruction-webng:latest
          ports:
            - containerPort: 80
