apiVersion: v1
kind: Service
metadata:
  name: econstruction-order-service
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
  selector:
    app: econstruction-order
