apiVersion: v1
kind: Pod
metadata:
  name: angular-app-pod
  labels:
    app: angular-app
spec:
  containers:
    - name: nginx-custom
      image: 127041487502.dkr.ecr.us-east-1.amazonaws.com/econstruction-webng:latest
      ports:
        - containerPort: 80
