apiVersion: apps/v1
kind: Deployment
metadata:
  name: econstruction-inventory
  labels:
    app: econstruction-inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: econstruction-inventory
  template:
    metadata:
      labels:
        app: econstruction-inventory
    spec:
      containers:
        - name: econstruction-inventory
          image: 127041487502.dkr.ecr.us-east-1.amazonaws.com/econstruction-inventory:latest
          ports:
            - containerPort: 7070
          env:
            - name: ASPNETCORE_URLS
              value: 'http://+:7070'