apiVersion: apps/v1
kind: Deployment
metadata:
  name: econstruction-notification
  labels:
    app: econstruction-notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: econstruction-notification
  template:
    metadata:
      labels:
        app: econstruction-notification
    spec:
      containers:
        - name: econstruction-notification
          image: 127041487502.dkr.ecr.us-east-1.amazonaws.com/econstruction-notification:latest
          ports:
            - containerPort: 4040
          env:
            - name: ASPNETCORE_URLS
              value: 'http://+:4040'
