apiVersion: v1
kind: Service
metadata:
  name: econstruction-inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 7070
      targetPort: 7070
      protocol: TCP
  selector:
    app: econstruction-inventory
