apiVersion: v1
kind: Service
metadata:
  name: econstruction-notification-service
spec:
  type: ClusterIP
  ports:
    - port: 4040
      targetPort: 4040
      protocol: TCP
  selector:
    app: econstruction-notification
