apiVersion: v1
kind: Pod
metadata:
  name: econstruction-inventory-pod
  labels:
    app: econstruction-inventory
spec:
  containers:
    - name: econstruction-inventory
      image: >-
        127041487502.dkr.ecr.us-east-1.amazonaws.com/econstruction-inventory:latest
      ports:
        - containerPort: 7070
      env:
        - name: ASPNETCORE_URLS
          value: 'http://+:7070'